config/routes.rb
Rails.application.routes.draw do
  
  #homepage static element/page
     root('sessions#welcome')
  
  resources :opinions

  resources :users, only: [:new, :create] do
    resources :mixtapes
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/welcome', to: 'sessions#welcome'
  
  delete '/logout', to: "sessions#logout"
  get '/logout', to: 'sessions#logout'

  
  get '/ran_tape', to: 'mixtapes#ran_tape'
  
  get '/current_user_tape', to: 'mixtapes#current_user_tape'
  
  
  get '/search', to: 'mixtapes#search'
  get '/recent_mixtape', to: 'mixtapes#most_recent'
  
  # get '/popular_mixtape', to: 'mixtapes#popular_tape'
  
  #ominauth
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  



end

app/models/mixtape.rb
class Mixtape < ApplicationRecord
    validates :title, :artist, presence: true

    #access to mixtape's owner
    belongs_to :user

    # access to mixtape's opinion
    has_many :opinions 
    
    # gives me @mixtape.users for all the users who gave an opinion

    has_many :users, through: :opinions

    def uploaded_at
        self.created_at.to_date
    end

    scope :most_recent, -> {order created_at: :desc}

    scope :search, -> (query) {where("title LIKE ?", "%#{query}%") }

    scope :ran_tape, -> {order('RANDOM()').first.title}

    # def ran_tape

    #     self.order('RANDOM()').first

    # end
    
    # def self.most_recent
    #     self.order(created_at: :desc)
    # end
    
    #scope :popular_tape, -> {order opinions.max_by :desc}
    

    # def popular_tape
    #     self.opinions.max_by
    # end


end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
    before_action :mixtape_true_creator,:no_go, only: [:edit, :update]
    before_action :redirect_if_not_logged, only: [:new, :create, :edit, :update, :index, :home, :logout]


    def index
        @mixtapes = Mixtape.all
        #@current_user ||= User.find_by_id(session[:user_id]) 
    end

    def current_user_tape
        @mixtapes = current_user.mixtapes
    end

    def show
        @mixtape = Mixtape.find_by(id: params[:id])
        #binding.pry
       
    end


    def new

        @mixtape = Mixtape.new(user_id: params[:user_id])
        
    end

    def create

        @mixtape = Mixtape.new(mixtape_params)
        
        if @mixtape.save
            redirect_to user_mixtape_path(current_user, @mixtape)
        else
            flash[:message] = @mixtape.errors.full_messages.to_sentence 
            redirect_to new_user_mixtape_path(current_user)
        end
    
    end

    
    
    def edit
         
        @mixtape = Mixtape.find_by(id: params[:id])

    end
    
    def update

        @mixtape = Mixtape.find_by(id: params[:id])
        @mixtape.update(mixtape_params)
        if @mixtape.valid?
            redirect_to user_mixtapes_path
            #above made adjustment with rails magic 
        end

    end

    def destroy

        @mixtape = Mixtape.find_by(id: params[:id])
        @mixtape.destroy
        redirect_to user_mixtapes_path

    end

    def most_recent
        @mixtapes = Mixtape.most_recent
        @mixtape = Mixtape.ran_tape
    
    end

    def ran_tape
        @mixtape = Mixtape.find_by(id: params[:id])
        
        @mixtape = Mixtape.ran_tape
        current_user
    end

  
    def search
        @mixtapes = Mixtape.search(params[:title])
    end

    # def popular_tape
    #     @mixtape = Mixtape.all.order(:opinion DESC )
    #     @user = current_user
    
    # end

   

    private
    
    def mixtape_params#(*args)
         params.require(:mixtape).permit(:title, :artist, :features, :artcover, :genre, :user_id)
        #params.require(:mixtape).permit(*args)
    end


end

app/helpers/mixtape_helper.rb
module MixtapeHelper
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper

    def current_user

        @current_user ||= User.find_by_id(session[:user_id])

    end

end

app/views/mixtapes/_mixtape.html.erb
<%= form_with(model: @mixtape, url: user_mixtapes_path) do |f| %>
    <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>
    <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
    </div>
    <%= f.hidden_field :user_id %> 
    <%= f.label :artcover %> <br>
    <%= f.text_field :artcover %> 
    
    <div class="field">
    <%= f.label :features %><br>
    <%= f.text_field :features %>
    </div>
    
    <div class="field">
   
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
    </div>
    <br>
    <%= f.submit 'Create Mixtape' %>

<% end %>

app/views/mixtapes/_opinion.html.erb
<li>
   
    <%= opinion.user.name %> - 
    <%= opinion.context %><br>
    <%= opinion.created_at%> <br>
   <% if mixtape_true_creator || true_user_opinion %>
    <%= link_to 'remove', opinion_path(opinion.mixtape, opinion), method: "delete" %>  
    <% end %>
</li>

app/views/mixtapes/current_user_tape.html.erb
<h1>  Mixtapes Uploaded by <%= current_user.name %> </h1>

<br>

<div>
<ul>
<% @mixtapes.each do |tap| %>
    <li> <%= link_to(tap.title, user_mixtape_path(tap.user, tap)) %> - created by: <%=tap.user.name %> <br> uploaded - <%=tap.uploaded_at %> </li>
<% end %>
</ul>
</div>

app/views/mixtapes/edit.html.erb
<h1>Mixtapes#edit</h1>



<H1> Edit Your Mixtape </H1>

<%= form_with(model: @mixtape, url: user_mixtape_path) do |f| %>

    <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>

    <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
    </div>

    <%= f.label :artcover %> <br>
    <%= f.text_field :artcover %> 
    
    <div class="field">
    <%= f.label :features %><br>
    <%= f.text_field :features %>
    </div>
    
    <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
    </div>
    <br>

    <%= f.submit 'Change Mixtape' %>


<% end %>

<%= button_to "Remove Mixtape", user_mixtape_path(@mixtape), method: "delete" %>

app/views/mixtapes/index.html.erb
<h1>Mixtapes#index</h1>


<div>
    <H1> WELCOME BACK: <%= @current_user.username %> </H1>

</div>

<div class= container>
<h3> List of Mixtapes uploaded </h3>
<ul>
<% @mixtapes.each do |tap| %>
    <li> <%= link_to(tap.title, user_mixtape_path(tap.user, tap)) %> - created by: <%=tap.user.name %> <br> uploaded - <%=tap.uploaded_at %> </li>
<% end %>
</ul>
</div>

app/views/mixtapes/most_recent.html.erb
<h1>recent_mixtape</h1>


<div class= container>

<h3> random mixtape to listen to </h3>

<%=  @mixtape %>
    
</div>

<div class= container>
<h1> Recent MIXTAPES Uploaded DESCENDING ORDER </h1>
<ul>
<% @mixtapes.each do |tap| %>
    <li> <%= link_to(tap.title, user_mixtape_path(tap.user, tap)) %><br> - created by: <%=tap.user.name %> <br> uploaded - <%=tap.uploaded_at %> </li>

    <% end %>
</ul>
</div>

app/views/mixtapes/new.html.erb
<h1>Mixtapes#new</h1>



<h1>     CREATE MIXTAPE    </h1>


<%= render partial: @mixtape %>

app/views/mixtapes/popular_tape.html.erb
<h1> popular tapes </h1>


<% @mixtape.each do |d| %>

    <%= d.title %>
    <%= d.popular_tape %>
<br>
<% end %>

app/views/mixtapes/ran_tape.html.erb
<h1> Our Choice For Today <h1>

<h3> You Should Search This Mixtape <h3>


 Mixtape title: <%= @mixtape  %>

app/views/mixtapes/search.html.erb
<h1>Mixtapes#search</h1>


<ul>
    <% @mixtapes.each do |tap| %>
        
        <li> <%= link_to tap.title, user_mixtape_path(current_user,tap) %> </li>
        
    <% end %>
</ul>

app/views/mixtapes/show.html.erb
<h1>Mixtapes#show</h1>

<h1> Created MixTape Show Page </h1>

<div> 
<H4> UPLOADED BY </H4>
<p> USERNAME: <%= @mixtape.user.name %> </p>

</div>

--------------------------------------------------------
<br>

 <div>
    
    <h1><%= @mixtape.title %></h1>
    
    <p> artist: <%= @mixtape.artist %> </p>
    
    <p>features: <%= @mixtape.features %> </p>
    
    <p> genre: <%= @mixtape.genre %> </P>
    
    <p> uploaded: <%= @mixtape.uploaded_at %> </p>

    <p> Number_of_Opinions: <%= @mixtape.opinions.count %> </p>
    
</div>

<% if mixtape_true_creator%>
<%= link_to 'Edit Mixtape', edit_user_mixtape_path(@mixtape) %>
<% end %>
<br>
<%= link_to 'View All Mixtapes', user_mixtapes_path %> 
<br>
-----------------------------

<%= form_with(model: Opinion.new, url: opinions_path) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :mixtape_id, value: @mixtape.id %>
    <%= f.text_area :context %>
    <%= f.submit :opinion %>
<% end %>

-----------------------------
<h1> "opinion's section" </h1>

<ul>
    <% @mixtape.opinions.each do |opinion| %>
        
    <li>
        <%= opinion.user.name %> - 
        <%= opinion.context %><br>
        <%= opinion.created_at%> <br>
       <% if mixtape_true_creator || true_user_opinion %>
        <%= link_to 'remove', opinion_path(opinion), method: "delete" %>  
        <% end %>
    </li>

    <% end %>

</ul>