config/routes.rb
Rails.application.routes.draw do
  
  #homepage static element/page
     root('sessions#welcome')
  
  resources :opinions

  resources :users, only: [:new, :create] do
    resources :mixtapes
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/welcome', to: 'sessions#welcome'
  
  delete '/logout', to: "sessions#logout"
  get '/logout', to: 'sessions#logout'

  
  get '/ran_tape', to: 'mixtapes#ran_tape'
  
  get '/current_user_tape', to: 'mixtapes#current_user_tape'
  
  
  get '/search', to: 'mixtapes#search'
  get '/recent_mixtape', to: 'mixtapes#most_recent'
  
  # get '/popular_mixtape', to: 'mixtapes#popular_tape'
  
  #ominauth
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  



end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/welcome">
            <%= image_tag('fdlogo.png', width: '80px', height: '25px') %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to 'home', root_path, class: 'nav-link active' %>
            </li>
            
            <%= form_with(url: search_path, method: 'get', class: 'd-flex') do |f|%>
                <%= f.text_field :title, class: "form-control me-2", placeholder: "Search for Mixtape" %>
                <%= f.submit :Submit, class: "form-control me-2" %>
                <%end%>
            
                <li>
                <%= link_to 'Random Choice', ran_tape_path, class: 'nav-item' %>
              </li>
                
              <li>
                <%= link_to 'Your Mixtapes', current_user_tape_path, class: 'nav-item' %>
              </li>

            <li>

            <%= link_to 'Create Mixtape', new_user_mixtape_path(current_user), class: 'nav-item' %> 
            </li>

            <li>
            <%= link_to 'Recent Release', recent_mixtape_path, class: 'nav-item' %> 
            </li>
            
            <li class="nav-item">
            <%= link_to 'logout', logout_path, method: "delete" %> 
            
            </li>
            Logged in as:
            <li class="nav-item">
            <%= current_user.name %>
            </li>
              
              </ul>
            
              
              <%end%>
              <% if logged_out? %>
              
              <li class="nav-item">
              <%= link_to 'login', login_path %> 
              </li>
              <li class="nav-item">
              <%= link_to 'register', signup_path %> 
              </li>
              <li class="nav-item">
              <%= link_to 'Google Login', "/auth/google_oauth2", method: "post" %> 
              </li>
              <% end %>
              
              </div>
              </div>
          
              </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mixtaper</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render(partial:"layouts/nav")%>
    <%= flash[:message] if flash[:message]%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>